import type { LLMExportRecord } from "../../types/export";
import type { UserPreferenceProfile } from "../../types/presentation";
import type { SeasonSignal } from "../../types/season";
import type { RegionMonthRecord } from "../../types/weather";
import { formatRegionLabel } from "../../utils/regionLabel";
import { classifyClimateSeason } from "../matrix/classifyClimateSeason";
import { calculatePersonalScore } from "../matrix/presets";
import { SCORING_MODEL_VERSION, THRESHOLD_VERSION } from "../matrix/scoringMetadata";

export function toLLMExportRecord(
  record: RegionMonthRecord,
  profile: UserPreferenceProfile,
  seasonSignal?: SeasonSignal,
): LLMExportRecord {
  const exportedAt = new Date().toISOString();
  const climateSeason = classifyClimateSeason(record);
  const personal = calculatePersonalScore(record, profile);
  const driverSummary =
    personal.drivers.length > 0
      ? personal.drivers
          .slice(0, 3)
          .map((driver) => `${driver.direction === "positive" ? "+" : "-"}${driver.metric}`)
          .join(", ")
      : null;
  const warningSummary = personal.warnings.length > 0 ? personal.warnings.join(" | ") : null;

  return {
    region_id: record.region.id,
    country_code: record.region.countryCode,
    country_name: record.region.countryName,
    region_name: record.region.regionName,
    city_name: record.region.cityName,
    display_name: formatRegionLabel(record.region),
    latitude: record.region.lat,
    longitude: record.region.lon,
    month: record.month,
    suitability_score: personal.score,
    suitability_band: personal.band,
    suitability_confidence: Number(personal.confidenceDetails.coverage.toFixed(2)),
    temperature_min_c: record.temperatureProfile?.minC ?? null,
    temperature_avg_c: record.temperatureProfile?.avgC ?? record.metrics.temperatureC.value,
    temperature_max_c: record.temperatureProfile?.maxC ?? null,
    temperature_c: record.metrics.temperatureC.value,
    temperature_unit: record.metrics.temperatureC.unit,
    temperature_status: record.metrics.temperatureC.status,
    temperature_source: record.metrics.temperatureC.sourceName,
    temperature_source_url: record.metrics.temperatureC.sourceUrl,
    temperature_last_updated: record.metrics.temperatureC.lastUpdated,
    rainfall_mm: record.metrics.rainfallMm.value,
    rainfall_unit: record.metrics.rainfallMm.unit,
    rainfall_status: record.metrics.rainfallMm.status,
    rainfall_source: record.metrics.rainfallMm.sourceName,
    rainfall_source_url: record.metrics.rainfallMm.sourceUrl,
    rainfall_last_updated: record.metrics.rainfallMm.lastUpdated,
    humidity_pct: record.metrics.humidityPct.value,
    humidity_unit: record.metrics.humidityPct.unit,
    humidity_status: record.metrics.humidityPct.status,
    humidity_source: record.metrics.humidityPct.sourceName,
    humidity_source_url: record.metrics.humidityPct.sourceUrl,
    humidity_last_updated: record.metrics.humidityPct.lastUpdated,
    wind_kph: record.metrics.windKph.value,
    wind_unit: record.metrics.windKph.unit,
    wind_status: record.metrics.windKph.status,
    wind_source: record.metrics.windKph.sourceName,
    wind_source_url: record.metrics.windKph.sourceUrl,
    wind_last_updated: record.metrics.windKph.lastUpdated,
    uv_index: record.metrics.uvIndex.value,
    uv_unit: record.metrics.uvIndex.unit,
    uv_status: record.metrics.uvIndex.status,
    uv_source: record.metrics.uvIndex.sourceName,
    uv_source_url: record.metrics.uvIndex.sourceUrl,
    uv_last_updated: record.metrics.uvIndex.lastUpdated,
    pm25: record.metrics.pm25.value,
    pm25_unit: record.metrics.pm25.unit,
    pm25_status: record.metrics.pm25.status,
    pm25_source: record.metrics.pm25.sourceName,
    pm25_source_url: record.metrics.pm25.sourceUrl,
    pm25_last_updated: record.metrics.pm25.lastUpdated,
    aqi: record.metrics.aqi.value,
    aqi_unit: record.metrics.aqi.unit,
    aqi_status: record.metrics.aqi.status,
    aqi_source: record.metrics.aqi.sourceName,
    aqi_source_url: record.metrics.aqi.sourceUrl,
    aqi_last_updated: record.metrics.aqi.lastUpdated,
    wave_height_m: record.metrics.waveHeightM.value,
    wave_height_unit: record.metrics.waveHeightM.unit,
    wave_height_status: record.metrics.waveHeightM.status,
    wave_height_source: record.metrics.waveHeightM.sourceName,
    wave_height_source_url: record.metrics.waveHeightM.sourceUrl,
    wave_height_last_updated: record.metrics.waveHeightM.lastUpdated,
    wave_period_s: record.metrics.wavePeriodS.value,
    wave_period_unit: record.metrics.wavePeriodS.unit,
    wave_period_status: record.metrics.wavePeriodS.status,
    wave_period_source: record.metrics.wavePeriodS.sourceName,
    wave_period_source_url: record.metrics.wavePeriodS.sourceUrl,
    wave_period_last_updated: record.metrics.wavePeriodS.lastUpdated,
    wave_direction_deg: record.metrics.waveDirectionDeg.value,
    wave_direction_unit: record.metrics.waveDirectionDeg.unit,
    wave_direction_status: record.metrics.waveDirectionDeg.status,
    wave_direction_source: record.metrics.waveDirectionDeg.sourceName,
    wave_direction_source_url: record.metrics.waveDirectionDeg.sourceUrl,
    wave_direction_last_updated: record.metrics.waveDirectionDeg.lastUpdated,
    flood_risk: record.metrics.floodRisk.value,
    flood_risk_unit: record.metrics.floodRisk.unit,
    flood_risk_status: record.metrics.floodRisk.status,
    flood_risk_source: record.metrics.floodRisk.sourceName,
    flood_risk_source_url: record.metrics.floodRisk.sourceUrl,
    flood_risk_last_updated: record.metrics.floodRisk.lastUpdated,
    storm_risk: record.metrics.stormRisk.value,
    storm_risk_unit: record.metrics.stormRisk.unit,
    storm_risk_status: record.metrics.stormRisk.status,
    storm_risk_source: record.metrics.stormRisk.sourceName,
    storm_risk_source_url: record.metrics.stormRisk.sourceUrl,
    storm_risk_last_updated: record.metrics.stormRisk.lastUpdated,
    season_label: seasonSignal?.seasonLabel ?? null,
    season_confidence: seasonSignal?.confidence ?? null,
    season_weather_index: seasonSignal?.weatherIndex ?? null,
    season_crowd_index: seasonSignal?.crowdIndex ?? null,
    season_price_index: seasonSignal?.priceIndex ?? null,
    season_reason: seasonSignal?.reasonText ?? null,
    season_sources: seasonSignal ? JSON.stringify(seasonSignal.sources) : null,
    climate_season_label: climateSeason.label,
    climate_season_reason: climateSeason.reason,
    market_season_label: seasonSignal?.seasonLabel ?? null,
    market_confidence_source: seasonSignal?.marketConfidenceSource ?? null,
    profile_temp_preference: profile.tempPreference,
    profile_humidity_preference: profile.humidityPreference,
    profile_rain_tolerance: profile.rainTolerance,
    profile_air_sensitivity: profile.airSensitivity,
    profile_uv_sensitivity: profile.uvSensitivity,
    profile_surf_enabled: profile.surfEnabled,
    profile_dealbreaker_avoid_heavy_rain: profile.dealbreakers.avoidHeavyRain,
    profile_dealbreaker_avoid_unhealthy_air: profile.dealbreakers.avoidUnhealthyAir,
    profile_dealbreaker_avoid_very_high_uv: profile.dealbreakers.avoidVeryHighUv,
    profile_dealbreaker_avoid_strong_wind: profile.dealbreakers.avoidStrongWind,
    profile_dealbreaker_coastal_only: profile.dealbreakers.coastalOnly,
    personal_driver_summary: driverSummary,
    personal_warning_summary: warningSummary,
    scoring_model_version: SCORING_MODEL_VERSION,
    threshold_version: THRESHOLD_VERSION,
    exported_at: exportedAt,
  };
}
