import type { CountryCode, SuitabilityBand } from "./weather";
import type { MarketConfidenceSource, SeasonConfidence, SeasonLabel } from "./season";
import type { UserPreferenceProfile } from "./presentation";

export interface LLMExportRecord {
  region_id: string;
  country_code: CountryCode;
  country_name: string;
  region_name: string;
  city_name: string;
  display_name: string;
  latitude: number;
  longitude: number;
  month: number;
  suitability_score: number;
  suitability_band: SuitabilityBand;
  suitability_confidence: number;
  temperature_min_c: number | null;
  temperature_avg_c: number | null;
  temperature_max_c: number | null;
  temperature_c: number | null;
  temperature_unit: string;
  temperature_status: string;
  temperature_source: string;
  temperature_source_url: string;
  temperature_last_updated: string;
  rainfall_mm: number | null;
  rainfall_unit: string;
  rainfall_status: string;
  rainfall_source: string;
  rainfall_source_url: string;
  rainfall_last_updated: string;
  humidity_pct: number | null;
  humidity_unit: string;
  humidity_status: string;
  humidity_source: string;
  humidity_source_url: string;
  humidity_last_updated: string;
  wind_kph: number | null;
  wind_unit: string;
  wind_status: string;
  wind_source: string;
  wind_source_url: string;
  wind_last_updated: string;
  uv_index: number | null;
  uv_unit: string;
  uv_status: string;
  uv_source: string;
  uv_source_url: string;
  uv_last_updated: string;
  pm25: number | null;
  pm25_unit: string;
  pm25_status: string;
  pm25_source: string;
  pm25_source_url: string;
  pm25_last_updated: string;
  aqi: number | null;
  aqi_unit: string;
  aqi_status: string;
  aqi_source: string;
  aqi_source_url: string;
  aqi_last_updated: string;
  wave_height_m?: number | null;
  wave_height_unit?: string;
  wave_height_status?: string;
  wave_height_source?: string;
  wave_height_source_url?: string;
  wave_height_last_updated?: string;
  wave_period_s?: number | null;
  wave_period_unit?: string;
  wave_period_status?: string;
  wave_period_source?: string;
  wave_period_source_url?: string;
  wave_period_last_updated?: string;
  wave_direction_deg?: number | null;
  wave_direction_unit?: string;
  wave_direction_status?: string;
  wave_direction_source?: string;
  wave_direction_source_url?: string;
  wave_direction_last_updated?: string;
  flood_risk: number | null;
  flood_risk_unit: string;
  flood_risk_status: string;
  flood_risk_source: string;
  flood_risk_source_url: string;
  flood_risk_last_updated: string;
  storm_risk: number | null;
  storm_risk_unit: string;
  storm_risk_status: string;
  storm_risk_source: string;
  storm_risk_source_url: string;
  storm_risk_last_updated: string;
  season_label?: SeasonLabel | null;
  season_confidence?: SeasonConfidence | null;
  season_weather_index?: number | null;
  season_crowd_index?: number | null;
  season_price_index?: number | null;
  season_reason?: string | null;
  season_sources?: string | null;
  climate_season_label?: "high" | "shoulder" | "off" | null;
  climate_season_reason?: string | null;
  market_season_label?: SeasonLabel | null;
  market_confidence_source?: MarketConfidenceSource | null;
  profile_temp_preference?: UserPreferenceProfile["tempPreference"];
  profile_humidity_preference?: UserPreferenceProfile["humidityPreference"];
  profile_rain_tolerance?: UserPreferenceProfile["rainTolerance"];
  profile_air_sensitivity?: UserPreferenceProfile["airSensitivity"];
  profile_uv_sensitivity?: UserPreferenceProfile["uvSensitivity"];
  profile_surf_enabled?: boolean;
  profile_dealbreaker_avoid_heavy_rain?: boolean;
  profile_dealbreaker_avoid_unhealthy_air?: boolean;
  profile_dealbreaker_avoid_very_high_uv?: boolean;
  profile_dealbreaker_avoid_strong_wind?: boolean;
  profile_dealbreaker_coastal_only?: boolean;
  personal_driver_summary?: string | null;
  personal_warning_summary?: string | null;
  scoring_model_version?: string;
  threshold_version?: string;
  exported_at: string;
}
